---
- name: Ensure servers exist
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Build server if needed
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ server_name }}"
        flavor: performance1-1
        image: ubuntu-1404-lts-trusty-tahr
        region: IAD
        key_name: EvanPublicIAD
        wait: yes
        state: present
        networks:
          - private
          - public
        meta:
          group: "{{ app_group }}"
      register: rax
